### PR TITLE
Correct 3 month ust rates for 2019 and add test to check future rates

### PR DESCRIPTION
**Pull request by jakemcaferty**

### CODE REVIEW

**Comment by jakemcaferty** [comment]
I was actually planning on using these rates as a basis for working on the `fit` functionality for the Ho-Lee model.  I thought it would be a good exercise since it actually aligns with material I'm currently studying for on my QFI Quant exam.

**Comment by jason-ash** [comment]
This is awesome! Thanks @jakemcaferty! Congratulations on your first contribution, (and the first non-me contribution 😄)!

**Review by jason-ash — APPROVED** [review]

**Comment by skyrad12** [comment]
Have you considered sourcing interest rates from FRED directly within your script, either in a load or test rates sense?

**Comment by jason-ash** [comment]
I've considered it, but decided it fell outside the scope of this library. This library's focus is on stochastic processes. The datasets are here for convenience only. There are great libraries that already exist for grabbing data from the Fed. Maybe an idea would be to add a section to the README pointing users in the right direction if that's what they're after.

**Pull request merged**
